/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as PrestasiRouteImport } from './routes/prestasi'
import { Route as JenjangRouteImport } from './routes/jenjang'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as BeritaRouteImport } from './routes/berita'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'

const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestasiRoute = PrestasiRouteImport.update({
  id: '/prestasi',
  path: '/prestasi',
  getParentRoute: () => rootRouteImport,
} as any)
const JenjangRoute = JenjangRouteImport.update({
  id: '/jenjang',
  path: '/jenjang',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaRoute = BeritaRouteImport.update({
  id: '/berita',
  path: '/berita',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/berita': typeof BeritaRoute
  '/galeri': typeof GaleriRoute
  '/jenjang': typeof JenjangRoute
  '/prestasi': typeof PrestasiRoute
  '/program': typeof ProgramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/berita': typeof BeritaRoute
  '/galeri': typeof GaleriRoute
  '/jenjang': typeof JenjangRoute
  '/prestasi': typeof PrestasiRoute
  '/program': typeof ProgramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/berita': typeof BeritaRoute
  '/galeri': typeof GaleriRoute
  '/jenjang': typeof JenjangRoute
  '/prestasi': typeof PrestasiRoute
  '/program': typeof ProgramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/berita'
    | '/galeri'
    | '/jenjang'
    | '/prestasi'
    | '/program'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/berita'
    | '/galeri'
    | '/jenjang'
    | '/prestasi'
    | '/program'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/berita'
    | '/galeri'
    | '/jenjang'
    | '/prestasi'
    | '/program'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  BeritaRoute: typeof BeritaRoute
  GaleriRoute: typeof GaleriRoute
  JenjangRoute: typeof JenjangRoute
  PrestasiRoute: typeof PrestasiRoute
  ProgramRoute: typeof ProgramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestasi': {
      id: '/prestasi'
      path: '/prestasi'
      fullPath: '/prestasi'
      preLoaderRoute: typeof PrestasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jenjang': {
      id: '/jenjang'
      path: '/jenjang'
      fullPath: '/jenjang'
      preLoaderRoute: typeof JenjangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita': {
      id: '/berita'
      path: '/berita'
      fullPath: '/berita'
      preLoaderRoute: typeof BeritaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  BeritaRoute: BeritaRoute,
  GaleriRoute: GaleriRoute,
  JenjangRoute: JenjangRoute,
  PrestasiRoute: PrestasiRoute,
  ProgramRoute: ProgramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
